### ISSUE TITLE
Redesign the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cvp-v2#1]
Take cvpglobal.com and update it to our current standards. 

Be sure to take into account the current navigation and what options you have design-wise to preserve her intention but also make it look better. 

due:
8-26-15   3p

**Comment by AaronAguilar** [comment]
Sorry, forgot to mention but here's the website: http://editllc.github.io/client-cvp-v2/

**Comment by AaronAguilar** [comment]
Updated it, cleaned it up and added Google Analytics.

**Comment by rodneystrong** [comment]
Client LOOOOVES the new design. 

Well done sir.
