### ISSUE TITLE
Add Indiegogo content

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cvp-v2#2]
Also, since we're talking about the website, can you create something at the bottom of the home page that reads something to effect of

Check Back Soon for A Link to Our Crowd funding Campaign Through
                ![indie](https://cloud.githubusercontent.com/assets/539962/12253870/f8ca30d4-b897-11e5-8124-6017c1016cad.png)
                Launching February 1 2016"

due:
1-12-16  5p

**Comment by rodneystrong** [comment]
Be sure to FTP The changes too.

**Comment by rampage1213** [comment]
Done! FTP!
